dist: trusty
notifications:
  hipchat:
    rooms:
      secure: XzwVqNcyT0qzVJ5TayVFB4d2ya5DepeWNGWsKWhAIMlbkVCaEFVWJq8MvcnNhDz9h7mqvrI3R6uSiabCOF2YOMLSr4V/ptlDRxUCsrr1f7pIxuOQXGHJo7FBvqxxuW4oGxSP80kSd/Cn2iUS/UcXwnOzj20FLXzXQ0A5NVywsqrqYAb3H9PReHyrAhTETbWZtINgW54CzkDVXmhPj7cregsPEJpM/+Z8jiMuzqYLhcEpXlJUsHnZm9elF+8KCMlWY0WI85A8/Z7aQzIuZfNY75/7yWaXeppnuzAAv31MV1Npw0nS4F9fy9DqS2jQkqYFBvAhWrA85kjMRtrWNtm9GHfJAQqvcoI+gxygfA7thklkQko/gO5KM07sftzWBye0JDT3gts/xOq7FrSuBd+UjFkUJtzm4DgS9JO/AV+bCH3RCREu9vduL+6T9GQOKZkKmTnbf81r8pysNlakrzns1IXDwfr8ecuO3M1tEpwHPoH8XMDdLqi7qCH6LPn+9rtgUONZ9EpgFKpQ/7YJS/vUp/v1coA1g5VOnblhaAD2LFB1asGYinVAQklzGuYrvg3wVnMmEUQAOvqHZyErTtTyduH2BIE0ua2tgSjp9ASEpiWVfGn1vGZ63ein8LR/WeZJ1wRAhkrMvMRamhHzj+1oaC5wJ5F37/t5uBr5ZH/+Npc=
sudo: required
services:
- docker
env:
  global:
  - DOCKER_IMAGE=puppet/lumogon
  - DOCKER_USER=johnmccabepuppet
  - secure: GMXDORlcSiInZDIu2pszOAhBZu8Feej3VMml5VgQVPR4R44U2nMu0azIJAMNnPZFOawYWNQotfVKIw3rFgSH0rJ9lHfRwh5i6bUiytGtDhji/c5QH2aUU8gg1c7hIGfMkcjs7dvni2fE1WZ3+sCSJQQwXhWFcgUJ3guX+dTcE4bBF4/T2Yhru0sZ41DXJwBw9Lo5Lp9/vkE8EImWMALTzhlNeOrSsfdtgkz/X5n6vufzjIsbdkdGbCELdCcYibeMAxeM+Qk9imxLaCr/OyU5gxpTiCOEkp8FUIgGrsx8q/veyk5DWxGMgGAmOHLAo6d57j7poPU26r+IkGWdItjmxWnjVcCDgDaUv88SnzQ7Hjh5nbd8RiKlnI+cr5IKPp1SUWliEA4W2IUAJBvIHJXW3fOj5gAE6mJHNYEfwElHkYOyAedCRLVipDO7PK0Lb89TGdk6x1k35oVGXQOHRJl/8jkJynF7YnI92rrK4wKHuufGh8ExyETv093dIM+wVWQmN42v4RgSSgy10IX3mQxrl3IUy6Ss6EaQVfK0rFHxxCJ/IOjQ2hh3Q6nW88ZGl826AxLJrymMylcxr/yc8RkWu41BtcNUuf7poBD5tGIVt2G29u9q73h2VGHuZD6Z7dKMGbuGkhgtnvkCFyd203uE26MhHp+UY6gQEdOfun6yMWA=
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
matrix:
  include:
  - go: 1.10.x
    language: go
    install: make bootstrap
    script:
    - make test
  - language: ruby
    rvm: 2.3.4
    cache: bundler
    services: docker
    bundler_args: "--without development"
    env: PUPPET_GEM_VERSION="~> 4.0"
    install:
    - make image
    - cd contrib/puppetlabs-lumogon && make bootstrap
    script: make vendor test
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    all_branches: true
