dist: trusty
sudo: required
services:
- docker
env:
  global:
  - DOCKER_IMAGE=puppet/lumogon
  - DOCKER_USER=jfryman
  - secure: Q5+WSF1b7tBzaVKWIIAOT4ItlcSj38eVMw5XAWkpw4XRaO1lu1awuvsx2XBDlZaLdcvm6S45HbM/6wX4/ZoBcv0rVx5Bd4ojranXEby4aIwPAxWx4hJ2plIgoQGWcRH576Nh7WumpW+kBllpYI8pcziW6bAA59SsX9OESBsmTK4+dSR8efBWUYQzTccsU0X+x+5HEot2wb/4j6/Xpis1zsMSEWL33j/KLSp3e4CE4DjoFONr3UiSII3RAmHjus/4C47S7bx1JGv3sZgQ96pVt0zZO4Au1Nn+R85caAJqm31Vx7mEDENYnLbfAKuGXWoRzV+1odFDsk5UUwRGEgc+w9+r0nrFfCn22NgCk5R5smmNr7yXbpt3ECLfuEglTkeD6qpyOckf5rgY0y834iQURYhEJPnh6v8f2C1XntDYsgyb0ni9Um6D2CYM4hp7yWw0aW+59Ia5cs/E5JgYIqsHuiAyoVuVcmnMXHhGwD+G8YhGCpahe1u0aNRGifdYmatzBXR8iGUh/RbEpXdIXQmpvgR2bFcfnuKIbV/WIVjejzxiFJmjSBYKs93J5BBJww7W8v2+e+WuDs5uiLpYtQFMeqaAua4NwxyQlyEKgAYTCQfy1DsjkKhWiTmlJ2b05LHE30RRKHYVbJRoW51xsTvE43wzmtAQ63vg5PUvwh6xnKs=
matrix:
  include:
  - go: 1.8
    language: go
    install: make bootstrap
    script:
    - make dependencies test
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  hipchat:
    rooms:
      secure: qOGrrKXJ0Uq5AwijRBjGtl2AlIJX/Zdy9F60JhUQlNluqyEgnx0hxcWy2oqHObQ0fD3yA5MQmLtf5WPSlQ3YPwOjjtSrtQn1w5c6d+D409BoZ7DrgJryvi7QsnP4v3uPlIM8MYC2GPrt0rKkw9yL7JTfmOMnGG1HE+yxVtdVvGEsEKE5TfGpNH6sgszgtp1dlrxgv4FJoNKENR9kIDOdLVxLU7nCYFWpHhVm/tpk7CmyqkoGMQ0FLGSHI1ae9s6Se6mChu8xg5rGSsWW0ZVkC7X6LEU/+7im2iWLC849UG3UAjznlNOuprNKU6P1JWJheByh45F8DmJHO6NjoHYRUvjgPN/JQ4igtRzF7hwm811gNviwsHlgQ2gRhyRIdMIUwPuxIev2Y8bHoh+3A3KSDuvY5qCbFpY5Zjq7t2ArXnO9a8m3AZEhWedRwYF6U+LeggOL/5wFbDhAvtwG9Pyojpuoxm7bUwsU5sL8bwdktSp4uxjdm+gAkVh99ysTCWL2JJ7CaA8Ossbr6sakWABPa06S3NAYRBNDqXBv7MkD9QrbETPSj11g+YY+QKcfuUYbYnF+doqGe2JBMnVeMHmKyErvgNI4otkxwgcqTJe9cqOmsx7d8F6B/hUm8xzKyY0vKK8MuoXfjiULPjYNIGhWDlknkiCoZ8tXxbj4bnO0Jf4=
